### ISSUE TITLE
ngettext fails in validators

### ISSUE THREAD

**Issue by piranha** [wtforms/wtforms#261]
So I have an app using flask-admin and it fails for me with an error:

```
  File "/v1/mkadmin/env_mkadmin/lib/python2.6/site-packages/wtforms/validators.py", line 101, in __call__
    'Field cannot be longer than %(max)d characters.', self.max)
  File "/v1/mkadmin/env_mkadmin/lib/python2.6/site-packages/wtforms/fields/core.py", line 174, in ngettext
    return self._translations.ngettext(singular, plural, n)
  File "/v1/mkadmin/env_mkadmin/lib/python2.6/site-packages/flask_admin/babel.py", line 21, in ngettext
    return ngettext(singular, plural, n)
  File "/v1/mkadmin/env_mkadmin/lib/python2.6/site-packages/flask_admin/babel.py", line 10, in ngettext
    return (singular if num == 1 else plural) % variables
KeyError: u'max'
```

So it seems that you have to pass `{'max': self.max}` to ngettext to get it working.

**Comment by citizen-stig** [comment]
I've noticed the same issue, I use python 3.5

**Comment by citizen-stig** [comment]
Steps to reproduce.

Install flask-admin without Babel, so Flask-Admin will use their own gettext implementation. This gettext tries to interpolate string, but without appropriate variables.

**Comment by mrjoes** [comment]
This was indeed problem in Flask-Admin and it was fixed.

**Comment by piranha** [comment]
Cool, thanks everybody!

**Comment by dxmo** [comment]
Hey,
I'm having similar issue although I am using flask-babelex. Any idea what the solution/workaround would be possible here?

Thanks for any tips!

`Traceback (most recent call last):
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask_admin/model/base.py", line 1973, in edit_view
    if self.validate_form(form):
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask_admin/model/base.py", line 1290, in validate_form
    return validate_form_on_submit(form)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask_admin/helpers.py", line 65, in validate_form_on_submit
    return is_form_submitted() and form.validate()
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/wtforms/validators.py", line 101, in __call__
    'Field cannot be longer than %(max)d characters.', self.max)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/wtforms/fields/core.py", line 174, in ngettext
    return self._translations.ngettext(singular, plural, n)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask_admin/babel.py", line 58, in ngettext
    return wtforms_domain.ngettext(singular, plural, n)
  File "/Users/igor/Documents/Tablehead/TableheadCMS/ENV/lib/python2.7/site-packages/flask_babelex/__init__.py", line 550, in ngettext
    return t.ungettext(singular, plural, num) % variables
KeyError: u'max'`
