### ISSUE TITLE
Cannot add fields in __new__

### ISSUE THREAD

**Issue by weltensturm** [wtforms/wtforms#319]
Fields that are added to a form class in __new__ cause an error: 
`from wtforms import Form, SelectField

class Test(Form):

    def __new__(cls, *args, **kwargs):
        cls.attr1 = SelectField('attr1')
        return super().__new__(cls, *args)

    attr2 = SelectField('attr2')

test = Test(attr1=1, attr2=2)
`
`
Traceback (most recent call last):
  File "src/pisa/forms/parts/test.py", line 12, in <module>
    test = Test(attr1=1, attr2=2)
  File "/srv/pisa/lib/python3.6/site-packages/wtforms/form.py", line 213, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/srv/pisa/lib/python3.6/site-packages/wtforms/form.py", line 274, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/srv/pisa/lib/python3.6/site-packages/wtforms/form.py", line 50, in __init__
    for name, unbound_field in itertools.chain(fields, extra_fields):
TypeError: 'NoneType' object is not iterable
`
In Form metaclass' __call__ function, the list of fields is built before anything else with the class happens. So the only sane way to add fields that depend on runtime values is in a factory function, but linters have a hard time registering fields that are added that way.

**Comment by josePhoenix** [comment]
A fix to this would simplify my code too. 👍

**Comment by azmeuk** [comment]
Dynamic forms can be done with BaseModel.
