### ISSUE TITLE
StringField default values not working on dynamic forms

### ISSUE THREAD

**Issue by Shellcat-Zero** [wtforms/wtforms#436]
I've had a hard time finding much documentation on how to properly handle dynamic forms, save for a few blog posts and stackoverflow issues.  All fields seem to work just fine except for StringField.  @davidism previously proposed multiple solutions to the issue, but I either misunderstood, or otherwise still failed to solve the problem.

The issue is that the default value does not get set, and results in an empty field. So in this case, it's `name.default`:
```python
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField
from wtforms.validators import DataRequired, Optional

def get_vals(var):
    typs = var.p_typs
    p_name = var.p_name
    return typs,p_name

class NewForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    typ1 = SelectField('Type', validators=[Optional()])

    def __init__(self,var):
        super(NewForm,self).__init__()
        typs,p_name = get_vals(var)

        self.typ1.choices = typs
        self.name.default = p_name
```
Then, this is used in routes.py as:
```python
    var.p_name = 'test name'
    var.p_typs = [(None, ' '), ('opt1', opt1'), ('opt2', 'opt2')]
    form = NewForm(var)
    if form.validate_on_submit():
        var.name = form.name.data.upper()
        var.typ1 = form.type1.data
```
This is wtforms version 2.2.1, and using Python 2.7 (due to incomplete Python 3 coverage in other libraries used elsewhere in the code). 

I've tried calling super() after the variable assignments, which results in a traceback:
```shell
Traceback (most recent call last):
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/myusername/Documents/myproject/quote/userint/app/routes.py", line 177, in details
    return render_template('details.html',  title='Part Details', form=form, grainxv=gxv, grainyv=gyv, tlen=tlen)
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/myusername/Documents/myproject/quote/userint/app/templates/details.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/myusername/Documents/myproject/quote/userint/app/templates/base.html", line 29, in top-level template code
    {% block content %}{% endblock %}
  File "/home/myusername/Documents/myproject/quote/userint/app/templates/details.html", line 27, in block "content"
    {{ form.customer() }}
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/wtforms/fields/core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/wtforms/widgets/core.py", line 323, in __call__
    for val, label, selected in field.iter_choices():
  File "/home/myusername/miniconda3/envs/p27/lib/python2.7/site-packages/wtforms/fields/core.py", line 454, in iter_choices
    for value, label in self.choices:
TypeError: 'NoneType' object is not iterable
```
Any help is much appreciated.

**Comment by davidism** [comment]
It looks like you just want to pass an object to the form, there's nothing dynamic in the fields.

```python
class Part:
    def __init__(self, name):
        self.p_name = name

class PartForm(Form):
    p_name = StringField('Name')

part = Part('wheel')
form = PartForm(obj=part)
```

**Comment by davidism** [comment]
I can't reproduce the issue with choices being `None`. Here's a simpler example:

```python
class Part:
    types = ['round', 'square', 'static']

    def __init__(self, name):
        self.p_name = name


class PartForm(Form):
    p_name = StringField('Name')
    typ = SelectField('Type')

    def __init__(self, *args, obj=None, **kwargs):
        super(PartForm, self).__init__(*args, **kwargs)

        if obj is not None:
            self.typ.choices = [(x, x) for x in obj.types]
```

**Comment by davidism** [comment]
Defaults are take from `obj` as shown before, or from the `data` kwargs, or from kwargs matching field names.

```python
form = PartForm(p_name="default value")
```

You shouldn't need to update the default in the constructor, you would pass the default in when initing the form.

**Comment by Shellcat-Zero** [comment]
Awesome, thanks @davidism. This works exactly as needed.

Small correction, the argument ordering should be changed from:
```python
def __init__(self, *args, obj=None, **kwargs):
        super(PartForm, self).__init__(*args, obj=obj, **kwargs)
```
to:
```python
def __init__(self, obj=None, *args, **kwargs):
        super(PartForm, self).__init__(obj=obj, *args, **kwargs)
```
to avoid a syntax error.
