### ISSUE TITLE
Regexp validator fails on MultipleFileField

### ISSUE THREAD

**Issue by maciejmatczak** [wtforms/wtforms#442]
Hi Guys,

Regexp validator fails on multiple file field - it validates on field.data which in this situation is a list.

(I wanted to clone the repo and try out new Regexp test case with list type field.data value, but I failed at running pytest on non-installed package and picking up whole validators tests...)

Cheers

**Comment by davidism** [comment]
I'm not sure what you would expect `Regexp` to validate even for a single file field, a file is not a string.

**Comment by maciejmatczak** [comment]
Well, just a filename exactly as it is stated in the docs for singular FileField: https://wtforms.readthedocs.io/en/stable/fields.html#wtforms.fields.FileField

Currently field.data is list of file names, that's why regexp validator fails.

**Comment by azmeuk** [comment]
I could reproduce with:

```python
>>> import wtforms
... import werkzeug.datastructures
... class F(wtforms.Form):
...     foo = wtforms.FileField(validators=[wtforms.validators.regexp(r'.*\.jpg$')])
... data = werkzeug.datastructures.ImmutableMultiDict({"foo": "blahblahblah.jpg"})
... F(data).validate()
True

>>> import wtforms
... import werkzeug.datastructures
... class F(wtforms.Form):
...     foo = wtforms.MultipleFileField(validators=[wtforms.validators.regexp(r'.*\.jpg$')])
... data = werkzeug.datastructures.ImmutableMultiDict({"foo": "blahblahblah.jpg"})
... F(data).validate()
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/azmeuk/dev/wtforms/wtforms/.tox/py38/lib/python3.8/site-packages/wtforms/form.py", line 324, in validate
    return super().validate(extra)
  File "/home/azmeuk/dev/wtforms/wtforms/.tox/py38/lib/python3.8/site-packages/wtforms/form.py", line 147, in validate
    if not field.validate(self, extra):
  File "/home/azmeuk/dev/wtforms/wtforms/.tox/py38/lib/python3.8/site-packages/wtforms/fields/core.py", line 268, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/azmeuk/dev/wtforms/wtforms/.tox/py38/lib/python3.8/site-packages/wtforms/fields/core.py", line 288, in _run_validation_chain
    validator(form, self)
  File "/home/azmeuk/dev/wtforms/wtforms/.tox/py38/lib/python3.8/site-packages/wtforms/validators.py", line 341, in __call__
    match = self.regex.match(field.data or "")
TypeError: expected string or bytes-like object

expected string or bytes-like object
```

**Comment by azmeuk** [comment]
`MultipleFileField`×`Regexp` seems a very specific case:

- Of all the fields, only `SelectMultipleField` and `MultipleFileField` store their data as a list, but `Regexp` is not pertinent on `SelectMultipleField` as the input is constrained in a defined set of values;
- Of all the validators, only `Regexp` seems pertinent to use on `MultipleFileField`.

**Comment by azmeuk** [comment]
We should fix this later if we work on #799
