### ISSUE TITLE
validators.NumberRange doesn't handle NaN

### ISSUE THREAD

**Issue by jon-brenner** [wtforms/wtforms#505]
Validating a `DecimalField` with a `NumberRange` validator throws a `decimal.InvalidOperation` exception when the value of the field is NaN. I would expect validation to fail instead
```
File "/usr/local/lib/python3.6/dist-packages/wtforms/form.py", line 310, in validate
  return super(Form, self).validate(extra)
File "/usr/local/lib/python3.6/dist-packages/wtforms/form.py", line 152, in validate
  if not field.validate(self, extra):
File "/usr/local/lib/python3.6/dist-packages/wtforms/fields/core.py", line 206, in validate
  stop_validation = self._run_validation_chain(form, chain)
File "/usr/local/lib/python3.6/dist-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
  validator(form, self)
File "/usr/local/lib/python3.6/dist-packages/wtforms/validators.py", line 134, in __call__
  if data is None or (self.min is not None and data < self.min) or 
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

**Comment by azmeuk** [comment]
I could reproduce this with both `master` and `2.2-maintenance`.

```python
>>> import wtforms                                                                                                                                                                             
>>> from tests.common import DummyPostData                                                                                                                                                     
>>> class F(wtforms.Form): 
...      a = wtforms.DecimalField(validators=[wtforms.validators.NumberRange(min=0, max=1)])                                                                                                                                                      
>>> F(DummyPostData({"a": "NaN"})).validate()                                                                                                                                                  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/azmeuk/dev/wtforms/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/azmeuk/dev/wtforms/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/azmeuk/dev/wtforms/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/azmeuk/dev/wtforms/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)  File "/home/azmeuk/dev/wtforms/wtforms/validators.py", line 134, in __call__    if data is None or (self.min is not None and data < self.min) or \decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
[<class 'decimal.InvalidOperation'>]
```
