### ISSUE TITLE
2.3.0 breaks rendering of SelectField when choices are a python set object

### ISSUE THREAD

**Issue by riptusk331** [wtforms/wtforms#588]
### Actual Behavior

```python

>>> from wtforms import Form, SelectField
>>> from wtforms.validators import DataRequired

>>> class MyForm(Form):
...     foo = SelectField('Bar', validators=[DataRequired()])

>>> f = MyForm()
>>> f.foo.choices = set([1, 2, 2, 3])

>>> str(f.foo)
```
results in
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../wtforms/fields/core.py", line 137, in __str__
    return self()
  File "../wtforms/fields/core.py", line 160, in __call__
    return self.meta.render_field(self, kwargs)
  File "../wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "../wtforms/widgets/core.py", line 300, in __call__
    for val, label, selected in field.iter_choices():
  File "../wtforms/fields/core.py", line 481, in iter_choices
    elif isinstance(self.choices[0], (list, tuple)):
TypeError: 'set' object is not subscriptable
```

### Environment

* Python version: 3.7
* wtforms version: 2.3.1

**Comment by riptusk331** [comment]
To be clear, I am running 2.3.1 but this stopped working properly with 2.3.0

**Comment by davidism** [comment]
Passing a set as choices doesn't make sense, it has no order and choices are an ordered list of items. Pass `choices=list(my_set)` or `choices=sorted(my_set)` if you need to use a set somewhere else.

**Comment by riptusk331** [comment]
thanks - why did it work in the old version?
