### ISSUE TITLE
Rendering error for BaseForm fields

### ISSUE THREAD

**Issue by azmeuk** [wtforms/wtforms#668]
### Actual Behavior

Rendering a field in a `BaseForm` raise an `AttributeError`:

```python
>>> f = wtforms.form.BaseForm({'foo': wtforms.StringField()})
>>> f["foo"]()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eloi/dev/wtforms/wtforms/.tox/py39/lib/python3.9/site-packages/wtforms/fields/core.py", line 198, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/eloi/dev/wtforms/wtforms/.tox/py39/lib/python3.9/site-packages/wtforms/meta.py", line 64, in render_field
    return field.widget(field, **render_kw)
  File "/home/eloi/dev/wtforms/wtforms/.tox/py39/lib/python3.9/site-packages/wtforms/widgets/core.py", line 174, in __call__
    kwargs["value"] = field._value()
  File "/home/eloi/dev/wtforms/wtforms/.tox/py39/lib/python3.9/site-packages/wtforms/fields/core.py", line 660, in _value
    return str(self.data) if self.data is not None else ""
AttributeError: 'StringField' object has no attribute 'data'
```

### Expected Behavior

```python
>>> f = wtforms.form.BaseForm({'foo':wtforms.StringField()})
>>> f["foo"]()
Markup('<input id="foo" name="foo" type="text" value="">')
```

### Environment

* Python version: 3.9.0
* wtforms version: 2.3.3 and master

**Comment by azmeuk** [comment]
In this snippet, the `BaseForm.process` method has not been called, and this explains the error. However there is no `BaseForm.__call__` method, so that may be another issue.
