### ISSUE TITLE
[2.3.x] ext_sqlalchemy test failures w/ sqlalchemy 1.4: TypeError: mapper() got an unexpected keyword argument 'order_by'

### ISSUE THREAD

**Issue by mgorny** [wtforms/wtforms#696]
It seems that sqlalchemy-1.4 has some API changes that cause test failures in ext_sqlalchemy tests. I see that it's been removed in 3.0.x... but then it's been removed in 2015 and still no 2.0.0 final, so maybe it's worth fixing.

If you prefer me just stripping ext_sqlalchemy from Gentoo and seeing what happens, please lemme know.

### Actual Behavior

```pytb
$ tox -e py39
[...]
...............................................................................................................................................................................................EEEEEE.......
======================================================================
ERROR: test_with_query_factory (ext_sqlalchemy.QuerySelectFieldTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 78, in setUp
    self._do_tables(mapper, engine)
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 56, in _do_tables
    mapper(Test, test_table, order_by=[test_table.c.name])
TypeError: mapper() got an unexpected keyword argument 'order_by'

======================================================================
ERROR: test_without_factory (ext_sqlalchemy.QuerySelectFieldTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 78, in setUp
    self._do_tables(mapper, engine)
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 56, in _do_tables
    mapper(Test, test_table, order_by=[test_table.c.name])
TypeError: mapper() got an unexpected keyword argument 'order_by'

======================================================================
ERROR: test_multiple_values_without_query_factory (ext_sqlalchemy.QuerySelectMultipleFieldTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 141, in setUp
    self._do_tables(mapper, engine)
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 56, in _do_tables
    mapper(Test, test_table, order_by=[test_table.c.name])
TypeError: mapper() got an unexpected keyword argument 'order_by'

======================================================================
ERROR: test_single_default_value (ext_sqlalchemy.QuerySelectMultipleFieldTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 141, in setUp
    self._do_tables(mapper, engine)
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 56, in _do_tables
    mapper(Test, test_table, order_by=[test_table.c.name])
TypeError: mapper() got an unexpected keyword argument 'order_by'

======================================================================
ERROR: test_single_value_without_factory (ext_sqlalchemy.QuerySelectMultipleFieldTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 141, in setUp
    self._do_tables(mapper, engine)
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 56, in _do_tables
    mapper(Test, test_table, order_by=[test_table.c.name])
TypeError: mapper() got an unexpected keyword argument 'order_by'

======================================================================
ERROR: test_unpopulated_default (ext_sqlalchemy.QuerySelectMultipleFieldTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 141, in setUp
    self._do_tables(mapper, engine)
  File "/tmp/wtforms/tests/ext_sqlalchemy.py", line 56, in _do_tables
    mapper(Test, test_table, order_by=[test_table.c.name])
TypeError: mapper() got an unexpected keyword argument 'order_by'

----------------------------------------------------------------------
Ran 204 tests in 0.489s

FAILED (errors=6)
```

### Expected Behavior

Tests passing ;-).

### Environment

* Python version: 3.9.5
* wtforms version: 2.3.3 (244c8d6b15accb3e2efd622241e5f7c1cc8abb9d)

**Comment by whb07** [comment]
When you grep for the "test_unpopulated_default" , it comes empty in this repo. Are you sure you shouldn't be raising this issue over with the flask sqlalchemy repo instead?

**Comment by davidism** [comment]
We're not supporting `ext.sqlalchemy` in this repo, I'd just disable the tests for it.
