### ISSUE TITLE
Form validator crash when calling with arbitrary data in Email

### ISSUE THREAD

**Issue by thehlopster** [wtforms/wtforms#774]
Calling the Form validator with arbitrary data in Email crashes the program due to an incomplete punicode string.

### Steps to reproduce:

1. Call the Form validator with `e@NS.XN--S`  in Email.
2. The program crashes due to the incomplete punicode string.

```py
from wtforms import StringField, Form
from wtforms.validators import DataRequired, Email

class LoginForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email()])
    
form = LoginForm(data={'email': 'e@NS.XN--S'})
if form.validate():
    print('Login successful!')
else:
    print('Form validation failed!')
```

### Actual Behavior
The program crashes due to the incomplete punicode string.

### Expected Behavior
The Form validator should validate the email address and return False.

### Environment

* Python version: 3.9.2
* wtforms version: 3.0.1

**Comment by azmeuk** [comment]
The `Email` validator uses the [email_validator](https://pypi.org/project/email-validator/) library to check emails validity. It seems to be ok with other punicode domains:

```python
>>> import email_validator
>>> email_validator.validate_email('contact@xn--nbl-cla1l.eu', check_deliverability=False)
<ValidatedEmail contact@nüblà.eu>
```

But your email address does not validate:

```python
>>> email_validator.validate_email('e@NS.XN--S', check_deliverability=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eloi/.cache/pypoetry/virtualenvs/canaille-9pOPObZA-py3.11/lib/python3.11/site-packages/email_validator/validate_email.py", line 120, in validate_email
    domain_part_info = validate_email_domain_name(domain_part, test_environment=test_environment, globally_deliverable=globally_deliverable)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.cache/pypoetry/virtualenvs/canaille-9pOPObZA-py3.11/lib/python3.11/site-packages/email_validator/syntax.py", line 409, in validate_email_domain_name
    raise EmailSyntaxError(f"The part after the @-sign is not valid IDNA ({e}).")
email_validator.exceptions_types.EmailSyntaxError: The part after the @-sign is not valid IDNA (Invalid A-label).
```

Is your domain even valid?
```python
>>> 'xn--nbl-cla1l.eu'.lower().encode("utf-8").decode("idna")
'nüblà.eu'
>>> 'XN--S'.lower().encode("utf-8").decode("idna")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeError: decoding with 'idna' codec failed (UnicodeError: decoding with 'punycode' codec failed (UnicodeError: incomplete punicode string))
```

Anyways, I don't think this is the responsibility of wtform here, you probably should dig on the [email_validator](https://github.com/JoshData/python-email-validator/issues) side.
